### ISSUE TITLE
digitaljs_online does not respond

### ISSUE THREAD

**Issue by hpsteidle** [tilk/digitaljs_online#57] opened 2024-01-19 10:59 UTC
Im a teacher for FPGA-Basics. Last year i found digitaljs to simulate verilog-hdl. This is a great tool. Today i tested digitaljs-online an it doesent work. When i click the Button "synthesize and simulate", there is no output. The application seems to be frozen. I tried it with different example-Circuits and different Browsers - on Win10.

**Comment by tilk** [comment] 2024-01-19 11:55
Unfortunately, the service is sometimes being abused, which sometimes leads to lockups. I've now introduced a request limit (per IP) and a connection limit (for the entire server). This might reduce the service's responsiveness, but it may help with the lockups.

**Comment by tilk** [comment] 2024-01-19 16:26
Duplicate of #55.

**Closed by tilk** 2024-01-19 16:26 UTC
